# Generated by Django 5.1 on 2024-09-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lastName',
        ),
    ]
