# Generated by Django 5.1 on 2024-09-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_appointment_age_remove_appointment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='transactionId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
