# Generated by Django 5.1 on 2024-09-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctor_date_joined_doctor_education_doctor_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='appointmentId',
        ),
    ]
