# Generated by Django 5.1 on 2024-09-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_review_appointmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='doctorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
    ]
